# Generated by Django 3.2.14 on 2023-03-17 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockIndex', models.CharField(max_length=20)),
                ('BlockTimeStrap', models.DateTimeField(auto_now_add=True)),
                ('BlockData', models.CharField(max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
                ('Blockhash', models.CharField(max_length=255)),
                ('BlockLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Block_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockIndex', models.CharField(max_length=20)),
                ('BlockTimeStrap', models.DateTimeField(auto_now_add=True)),
                ('BlockData', models.CharField(max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
                ('Blockhash', models.CharField(max_length=255)),
                ('BlockLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.block_1')),
            ],
        ),
        migrations.CreateModel(
            name='Block_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockIndex', models.CharField(max_length=20)),
                ('BlockTimeStrap', models.DateTimeField(auto_now_add=True)),
                ('BlockData', models.CharField(max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
                ('Blockhash', models.CharField(max_length=255)),
                ('BlockLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.block_2')),
            ],
        ),
        migrations.CreateModel(
            name='Block_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockIndex', models.CharField(max_length=20)),
                ('BlockTimeStrap', models.DateTimeField(auto_now_add=True)),
                ('BlockData', models.CharField(max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
                ('Blockhash', models.CharField(max_length=255)),
                ('BlockLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.block_3')),
            ],
        ),
    ]
