# Generated by Django 3.2.14 on 2023-03-29 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0001_initial'),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block_2',
            name='MedicineBlock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manu.medicine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block_3',
            name='MedicineBlock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manu.medicine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block_4',
            name='MedicineBlock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manu.medicine'),
            preserve_default=False,
        ),
    ]
