# Generated by Django 3.2.14 on 2023-04-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
