# Generated by Django 3.2.14 on 2023-04-01 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0002_alter_cartitems_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('payment_status', models.BooleanField(default=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manu.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
