# Generated by Django 3.2.14 on 2023-03-29 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('distributer_price', models.FloatField()),
                ('MRP', models.IntegerField()),
                ('date_of_manufacture', models.DateField()),
                ('image', models.FileField(upload_to='medicine_image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
